#!/bin/bash

bin=~/.dropbox-dist/dropboxd
log=~/log/dropbox.log
touch $log
echo ">> starting dropbox daemon... $(date)" | tee -a $log
echo ">> logfile: $log" | tee -a $log

nohup $bin > $log 2>&1  &

